package h11.providers;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

/**
 * Provide a JUnit test with a random L-System and
 * a textual representation of that system as
 * generated by {@link LSystemToRandomLinesConverter}.
 */
public class ProjectionsWithLinesProvider extends ProjectionsProvider implements ArgumentsProvider {

    /**
     * The {@link LSystemToRandomLinesConverter} to use.
     */
    private final LSystemToRandomLinesConverter converter = new LSystemToRandomLinesConverter(random);

    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext extensionContext) {
        return generateProjections()
        .map(s ->
                Arguments.of(s, converter.lSystemAsLines(s)));
    }
}
